platform :ios, '14.0'
source 'https://cdn.cocoapods.org'

target 'iosApp' do
  use_frameworks!
  pod 'shared', :path => '../shared'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      # Set correct JAVA_HOME for Kotlin build
      config.build_settings['JAVA_HOME'] = '/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home'
    end
  end
end